_wandb:
    value:
        cli_version: 0.23.0
        e:
            n1eaaquqkfb84ddki14lrxrltjhx6ohg:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 8
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "999594913792"
                        used: "783650914304"
                email: mohabhelp@gmail.com
                executable: C:\Python313\python.exe
                gpu: NVIDIA GeForce RTX 2070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2304
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 2070
                      uuid: GPU-dc3d745a-e1ef-e5ad-255b-8fdfc7057585
                host: DESKTOP-FT5AR5G
                memory:
                    total: "17110953984"
                os: Windows-10-10.0.19045-SP0
                program: c:\Users\mohab\Desktop\M\train.py
                python: CPython 3.13.1
                root: c:\Users\mohab\Desktop\M
                startedAt: "2025-11-13T23:30:38.118225Z"
                writerId: n1eaaquqkfb84ddki14lrxrltjhx6ohg
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.13.1
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
agent:
    value: DQNAgent
batch_size:
    value: 64
env_id:
    value: Pendulum-v1
epsilon_decay:
    value: 2500
epsilon_end:
    value: 0.01
epsilon_start:
    value: 1
gamma:
    value: 0.99
learning_rate:
    value: 0.001
memory_size:
    value: 10000
target_update_freq:
    value: 10
tau:
    value: 0.005
