_wandb:
    value:
        cli_version: 0.23.0
        e:
            maedpcg939rhux1eu6vunu24h6zfc9e0:
                codePath: test.py
                codePathLocal: test.py
                cpu_count: 8
                cpu_count_logical: 8
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "999594913792"
                        used: "785441198080"
                email: mohabhelp@gmail.com
                executable: C:\Python313\python.exe
                gpu: NVIDIA GeForce RTX 2070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2304
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 2070
                      uuid: GPU-dc3d745a-e1ef-e5ad-255b-8fdfc7057585
                host: DESKTOP-FT5AR5G
                memory:
                    total: "17110953984"
                os: Windows-10-10.0.19045-SP0
                program: c:\Users\mohab\Desktop\M\test.py
                python: CPython 3.13.1
                root: c:\Users\mohab\Desktop\M
                startedAt: "2025-11-14T02:04:23.621840Z"
                writerId: maedpcg939rhux1eu6vunu24h6zfc9e0
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.13.1
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
agent:
    value: DQNAgent
env_id:
    value: CartPole-v1
episodes:
    value: 100
model_path:
    value: models\DQNAgent\CartPole-v1.pth
