_wandb:
    value:
        cli_version: 0.23.0
        e:
            r9xww8l4idqyd4u3ihzcie75zu1nv9rl:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 8
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "999594913792"
                        used: "785574141952"
                executable: C:\Python313\python.exe
                git:
                    commit: 996d035648e31ec4005fc882d28b37f6cd1de25b
                    remote: https://github.com/MohabYasser2/Assignment_2_RL.git
                gpu: NVIDIA GeForce RTX 2070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2304
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 2070
                      uuid: GPU-dc3d745a-e1ef-e5ad-255b-8fdfc7057585
                host: DESKTOP-FT5AR5G
                memory:
                    total: "17110953984"
                os: Windows-10-10.0.19045-SP0
                program: c:\Users\mohab\Desktop\M\train.py
                python: CPython 3.13.1
                root: c:\Users\mohab\Desktop\M
                startedAt: "2025-11-14T03:44:47.912110Z"
                writerId: r9xww8l4idqyd4u3ihzcie75zu1nv9rl
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.13.1
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
agent:
    value: DQNAgent
batch_size:
    value: 64
env_id:
    value: Acrobot-v1
epsilon_decay:
    value: 5000
epsilon_end:
    value: 0.05
epsilon_start:
    value: 1
gamma:
    value: 0.99
learning_rate:
    value: 0.0005
memory_size:
    value: 10000
target_update_freq:
    value: 10
tau:
    value: 0.005
